// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHev4V1TuAPVcWBrwauKP8y7apI6pEjRQ',
    appId: '1:887688847568:web:77009da9a2089e8842bed5',
    messagingSenderId: '887688847568',
    projectId: 'firstapp1-5dfa5',
    authDomain: 'firstapp1-5dfa5.firebaseapp.com',
    storageBucket: 'firstapp1-5dfa5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlq0jyAa2-GflBPQ4Nfb7rjpHPnpBwXMk',
    appId: '1:887688847568:android:f0e8d6ddb7c1f1c042bed5',
    messagingSenderId: '887688847568',
    projectId: 'firstapp1-5dfa5',
    storageBucket: 'firstapp1-5dfa5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL91O8D2I_xDUntPgvRm_3HE1Gjskz8UU',
    appId: '1:887688847568:ios:efd68100b894376042bed5',
    messagingSenderId: '887688847568',
    projectId: 'firstapp1-5dfa5',
    storageBucket: 'firstapp1-5dfa5.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL91O8D2I_xDUntPgvRm_3HE1Gjskz8UU',
    appId: '1:887688847568:ios:efd68100b894376042bed5',
    messagingSenderId: '887688847568',
    projectId: 'firstapp1-5dfa5',
    storageBucket: 'firstapp1-5dfa5.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHev4V1TuAPVcWBrwauKP8y7apI6pEjRQ',
    appId: '1:887688847568:web:77009da9a2089e8842bed5',
    messagingSenderId: '887688847568',
    projectId: 'firstapp1-5dfa5',
    authDomain: 'firstapp1-5dfa5.firebaseapp.com',
    storageBucket: 'firstapp1-5dfa5.firebasestorage.app',
  );
}
